spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:http://localhost:8888
#jwt:
#  secret: ${JWT_SECRET}
# as a Config server pr add hai
#  eureka:
#    client:
#      serviceUrl:
#        defaultZone: http://localhost:8761/eureka
#
#  server:
#    port: 8080
