spring.application.name=ai-service
spring.config.import= optional:configserver:http://localhost:8888


# Config kr diya hai config server pr
#server.port=8083
#
## New Spring Boot Format (Bina 'data' word ke [spring.mongodb] in spring 4.0+ version)
#spring.data.mongodb.uri=mongodb://localhost:27017/fitness_aiRecommendation
#
#eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
#
#spring.kafka.bootstrap-servers = localhost:9092
#spring.kafka.consumer.group-id = activity-processor-group
#spring.kafka.consumer.key-deserializer = org.apache.kafka.common.serialization.StringDeserializer
#spring.kafka.consumer.value-deserializer = org.springframework.kafka.support.serializer.JsonDeserializer
## type header ->  com.fit....acitivityservice.model (object ka type) usko use na kiya jaye we create our type
#spring.kafka.consumer.properties.spring.json.use.type.use.header=false
##  json serializable (jo value ayegi) kis class se map hoga uska type
#spring.kafka.consumer.properties.spring.json.value.default.type=com.fitness.aiservice.models.Activity
## "*" all packages ke class to accept
#spring.kafka.consumer.properties.spring.json.trusted.packages = "*"
#kafka.topic.name = ai-events
#
## value fetch from env of intellij
#gemini.api.url= ${GEMINI_URL}
#gemini.api.key= ${GEMINI_KEY}
