spring.application.name=eureka
server.port=8761
# config eureka // ye eureka bhi service hai so isilye
# hum kah rahe khud ko service jaise register mt kro u are server
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false