spring:
  application:
    name: configserver
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
          # sari cofig ko yaha fetch kro

server:
  port: 8888